name: Get and cache dependencys
description: Get the code and cache dependencies for faster builds #  Description of the composite action
inputs:  
  caching:  
    description: 'Whether to cache dependencies' #  Input to control caching behavior
    required: false
    default: 'true'
outputs: 
  used-cache:
    description: 'Whether the cache was hit (true/false)'
    value: ${{ steps.install.outputs.cache}} # Correctly reference the cache step's output

runs:
  using: composite
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }} #  Conditional caching based on input above
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        # Add a restore-keys to help with partial hits if necessary
        restore-keys: |
          deps-node-modules-
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'  #  Install if cache miss or caching disabled
      run: |
        npm ci
        echo "inputs.caching" >> $GITHUB_OUTPUT #  Output to indicate caching status
      shell: bash
